import { useTranslation } from "@/contexts/language-context";

const en = {
  ecosystem: "SMART CONTRACT ECOSYSTEM",
  home: "Home",
  explore: "Explore products",
  dashboard: "Open dashboard",
  heroTitle: "Your next chapter.",
  heroAccent: "Connected.",
  heroBody:
    "A considered space for your Web3 life. Explore your network, follow on-chain activity, and discover digital tools — all in one place.",
  heroNote: "Explore freely. Connect your wallet when you’re ready.",
  network: "BNB Chain",
  networkCaption: "On-chain workspace",
  selfCustody: "Your wallet. Your control.",
  selfCustodyBody: "Review and sign transactions in your own wallet.",
  builtFor: "BUILT AROUND YOU",
  featuresTitle: "Less searching. More doing.",
  featuresBody: "One connected workspace, with a clear place for everything.",
  overview: "A clearer overview",
  overviewBody:
    "Your rounds, network activity and contract data, brought together in a focused dashboard.",
  account: "Your personal workspace",
  accountBody:
    "Look up a wallet, follow your activity and manage account preferences.",
  networkTitle: "See the bigger picture",
  networkBody:
    "Explore your referral network and follow its connections in an interactive view.",
  academy: "Learn at your own pace",
  academyBody:
    "Explore practical guides to Web3, wallet security and AI prompting.",
  collection: "THE DIGITAL COLLECTION",
  productsTitle: "Useful by design.",
  productsBody:
    "Discover the tools, guides and digital services in the smart contract ecosystem. Availability is shown on every product.",
  allProducts: "All products",
  tools: "Web3 tools",
  learning: "Learning",
  digital: "Digital services",
  entertainment: "Games",
  search: "Search products…",
  searchLabel: "Search products by name or description",
  results: "products",
  clear: "Clear filters",
  noResults: "Nothing here just yet",
  noResultsBody: "Try another search or explore a different category.",
  featured: "Selected for you",
  featuredNote: "A few good places to begin.",
  open: "Explore",
  available: "Available",
  soon: "Coming soon",
  education: "Learning",
  start: "MAKE YOURSELF AT HOME",
  startTitle: "A simple way in.",
  stepOne: "Explore the workspace",
  stepOneBody:
    "Get familiar with the dashboard, products and learning resources.",
  stepTwo: "Connect your wallet",
  stepTwoBody: "Choose your preferred wallet. Your keys stay with you.",
  stepThree: "Make your next move",
  stepThreeBody: "Review the details and fees before signing any transaction.",
  faq: "A little clarity.",
  faqLabel: "GOOD TO KNOW",
  faqLink: "Visit the help center",
  ctaTitle: "Everything starts with a little curiosity.",
  ctaBody: "Explore the ecosystem. Your workspace is ready when you are.",
  footer: "A connected space for Web3.",
  platform: "Platform",
  resources: "Resources",
  help: "Help center",
  preferences: "Preferences",
  learn: "Learning center",
  history: "Activity history",
  user: "My workspace",
  products: "Products",
  swap: "Swap",
  genealogy: "My network",
  register: "Registration",
  charge: "Top up",
  disclaimer:
    "On-chain transactions involve fees and risk. Review each action before signing.",
  welcome: "YOUR WORKSPACE",
  welcomeTitle: "Good to have you here.",
  welcomeBody:
    "A clear view of your network, with your next action always within reach.",
  quick: "Quick access",
  quickBody: "Your most useful destinations, one tap away.",
  userTitle: "Your wallet. Your workspace.",
  userBody:
    "Find your account, explore your network and keep track of your activity.",
  accountTitle: "Make it yours.",
  accountSettings:
    "Your preferences, wallet settings and account controls, together in one place.",
  connect: "Connect wallet",
  changeNetwork: "Switch network",
  disconnected: "Wallet not connected",
  connected: "Wallet connected",
  workspaceHint: "Connect a wallet or search an address to see account data.",
  viewAll: "View all",
  activity: "Network overview",
  activityHint: "Data is read from the configured smart contracts.",
  supportTitle: "Need a hand?",
  supportBody: "Find your next step in the ecosystem guide.",
  menu: "Open navigation",
  closeMenu: "Close navigation",
  navLabel: "Main navigation",
  skip: "Skip to content",
  mobileNav: "Quick navigation",
  catalogEyebrow: "EXPLORE THE ECOSYSTEM",
  catalogTitle: "One ecosystem. More possibilities.",
  catalogBody:
    "From everyday tools to your next new skill. Find what you need, and see what’s on the way.",
  productDetails: "What’s included",
  collectionAlt:
    "Glass shield, metal digital cards and a book representing the ecosystem’s digital collection",
  networkAlt:
    "Blue glass and titanium loop surrounding connected network nodes",
  educationTitle: "A little knowledge. A new perspective.",
  educationBody:
    "Understand the tools before you use them. Start with the basics or explore an interactive simulator.",
};
type Copy = { [K in keyof typeof en]: string };
const fa: Copy = {
  ecosystem: "اکوسیستم قرارداد هوشمند",
  home: "خانه",
  explore: "کشف محصولات",
  dashboard: "ورود به داشبورد",
  heroTitle: "فصل تازهٔ شما؛",
  heroAccent: "به‌هم‌پیوسته.",
  heroBody:
    "فضایی یکپارچه برای دنیای وب۳ شما. شبکه‌تان را بشناسید، فعالیت‌های روی زنجیره را دنبال کنید و ابزارهای دیجیتال را کشف کنید.",
  heroNote: "آزادانه بگردید؛ هر وقت آماده بودید، کیف پولتان را متصل کنید.",
  network: "شبکهٔ BNB",
  networkCaption: "فضای کار روی زنجیره",
  selfCustody: "کیف پول شما، کنترل شما.",
  selfCustodyBody: "تراکنش‌ها را در کیف پول خودتان بررسی و امضا کنید.",
  builtFor: "برای تجربهٔ بهتر شما",
  featuresTitle: "دسترسی آسان‌تر. تجربه‌ای روان‌تر.",
  featuresBody: "یک فضای کار منظم که هر چیز در آن جای خودش را دارد.",
  overview: "نمایی روشن‌تر",
  overviewBody: "راندها، فعالیت شبکه و اطلاعات قرارداد را یک‌جا و مرتب ببینید.",
  account: "فضای شخصی شما",
  accountBody:
    "کیف پول را جست‌وجو کنید، فعالیت‌ها را ببینید و تنظیمات حساب را مدیریت کنید.",
  networkTitle: "تصویر کامل شبکه",
  networkBody: "شبکهٔ معرفی و ارتباط‌های آن را در نمایی تعاملی دنبال کنید.",
  academy: "با ریتم خودتان یاد بگیرید",
  academyBody: "راهنماهای کاربردی وب۳، امنیت کیف پول و پرامت‌نویسی را بخوانید.",
  collection: "مجموعهٔ دیجیتال اکوسیستم",
  productsTitle: "زیبا، ساده، کاربردی.",
  productsBody:
    "ابزارها، راهنماها و خدمات دیجیتال اکوسیستم را کشف کنید. وضعیت دسترسی هر محصول مشخص است.",
  allProducts: "همهٔ محصولات",
  tools: "ابزارهای وب۳",
  learning: "آموزش",
  digital: "خدمات دیجیتال",
  entertainment: "بازی‌ها",
  search: "جست‌وجوی محصول…",
  searchLabel: "جست‌وجو در نام و توضیحات محصولات",
  results: "محصول",
  clear: "پاک‌کردن فیلترها",
  noResults: "محصولی پیدا نشد",
  noResultsBody: "عبارت دیگری بنویسید یا دسته‌بندی را تغییر دهید.",
  featured: "پیشنهاد برای شروع",
  featuredNote: "چند مسیر کاربردی برای آشنایی بیشتر.",
  open: "مشاهده",
  available: "در دسترس",
  soon: "به‌زودی",
  education: "آموزشی",
  start: "شروعی ساده",
  startTitle: "قدم‌به‌قدم، کنار شما.",
  stepOne: "فضا را بشناسید",
  stepOneBody: "با داشبورد، محصولات و منابع آموزشی آشنا شوید.",
  stepTwo: "کیف پول را متصل کنید",
  stepTwoBody:
    "کیف پول دلخواهتان را انتخاب کنید. کلیدهای شما نزد خودتان می‌ماند.",
  stepThree: "قدم بعدی را بردارید",
  stepThreeBody: "قبل از امضای هر تراکنش، جزئیات و کارمزد آن را بررسی کنید.",
  faq: "پاسخ‌های روشن.",
  faqLabel: "خوب است بدانید",
  faqLink: "رفتن به مرکز راهنما",
  ctaTitle: "یک شروع تازه، با کمی کنجکاوی.",
  ctaBody: "اکوسیستم را کشف کنید. فضای کار شما منتظرتان است.",
  footer: "فضایی به‌هم‌پیوسته برای وب۳.",
  platform: "پلتفرم",
  resources: "منابع",
  help: "مرکز راهنما",
  preferences: "تنظیمات",
  learn: "مرکز آموزش",
  history: "تاریخچهٔ فعالیت",
  user: "پنل کاربری",
  products: "محصولات",
  swap: "تبدیل ارز",
  genealogy: "شبکهٔ من",
  register: "ثبت‌نام",
  charge: "شارژ حساب",
  disclaimer:
    "تراکنش‌های روی زنجیره کارمزد و ریسک دارند. پیش از امضا، جزئیات هر اقدام را بررسی کنید.",
  welcome: "فضای کار شما",
  welcomeTitle: "به اکوسیستم خوش آمدید.",
  welcomeBody: "نمایی روشن از شبکه، با دسترسی سریع به کارهایی که نیاز دارید.",
  quick: "دسترسی سریع",
  quickBody: "مسیرهای پرکاربرد، همیشه در دسترس شما.",
  userTitle: "کیف پول شما، فضای شما.",
  userBody:
    "حسابتان را پیدا کنید، شبکه را ببینید و فعالیت‌هایتان را دنبال کنید.",
  accountTitle: "به سلیقهٔ خودتان.",
  accountSettings: "تنظیمات شخصی، کیف پول و کنترل‌های حساب، همگی در یک‌جا.",
  connect: "اتصال کیف پول",
  changeNetwork: "تغییر شبکه",
  disconnected: "کیف پول متصل نیست",
  connected: "کیف پول متصل است",
  workspaceHint:
    "برای مشاهدهٔ اطلاعات حساب، کیف پول را متصل یا آدرسی را جست‌وجو کنید.",
  viewAll: "مشاهدهٔ همه",
  activity: "نمای کلی شبکه",
  activityHint: "اطلاعات از قراردادهای هوشمند تنظیم‌شده خوانده می‌شود.",
  supportTitle: "راهنمایی می‌خواهید؟",
  supportBody: "قدم بعدی را در راهنمای اکوسیستم پیدا کنید.",
  menu: "بازکردن منو",
  closeMenu: "بستن منو",
  navLabel: "منوی اصلی",
  skip: "رفتن به محتوای اصلی",
  mobileNav: "دسترسی سریع موبایل",
  catalogEyebrow: "کشف اکوسیستم",
  catalogTitle: "یک دنیا، فرصت‌های تازه.",
  catalogBody:
    "از ابزارهای روزمره تا مهارتی تازه؛ آنچه نیاز دارید پیدا کنید و با محصولات آینده آشنا شوید.",
  productDetails: "امکانات محصول",
  collectionAlt:
    "سپر شیشه‌ای، کارت‌های فلزی و کتاب؛ نمادی از مجموعهٔ دیجیتال اکوسیستم",
  networkAlt: "حلقه‌ای از شیشهٔ آبی و تیتانیوم، پیرامون گره‌های متصل شبکه",
  educationTitle: "دانش بیشتر، نگاه تازه‌تر.",
  educationBody:
    "پیش از استفاده، ابزارها را بشناسید. از مبانی شروع کنید یا به سراغ شبیه‌ساز تعاملی بروید.",
};
export function useExperienceCopy(): Copy {
  return useTranslation().locale === "fa" ? fa : en;
}
