export const roundWindowAbi = [
  {
    inputs: [{ internalType: "address", name: "_factory", type: "address" }],
    stateMutability: "payable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyVoted", type: "error" },
  { inputs: [], name: "EmergencyShutdown", type: "error" },
  { inputs: [], name: "InsufficientPayment", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  { inputs: [], name: "InvalidStartBox", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "MinimumNodesRequired",
    type: "error",
  },
  { inputs: [], name: "OnlyLatestWindow", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "TimeException", type: "error" },
  { inputs: [], name: "UnsentValue", type: "error" },
  { inputs: [], name: "UserNotFound", type: "error" },
  { inputs: [], name: "WindowClosed", type: "error" },
  {
    inputs: [],
    name: "LatestWindow",
    outputs: [{ internalType: "address", name: "window", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint24", name: "startBox", type: "uint24" },
      { internalType: "address", name: "direct", type: "address" },
      { internalType: "address", name: "referral", type: "address" },
    ],
    name: "begin",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint24", name: "targetBox", type: "uint24" }],
    name: "chargeAccount",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "nodes", type: "uint256" },
      { internalType: "bool", name: "devPool", type: "bool" },
    ],
    name: "distributeMatchingBonuses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "direct", type: "address" }],
    name: "getBestReferralForDirect",
    outputs: [{ internalType: "address", name: "referral", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "roundsAgo", type: "uint256" }],
    name: "getMainBulkInfo",
    outputs: [
      { internalType: "address", name: "roundWindow", type: "address" },
      { internalType: "uint256", name: "userCount_", type: "uint256" },
      { internalType: "string", name: "pointValue_", type: "string" },
      { internalType: "uint256", name: "roundPoints_", type: "uint256" },
      { internalType: "string", name: "roundEnteredUSD_", type: "string" },
      { internalType: "string", name: "allEnteredUSD_", type: "string" },
      { internalType: "string", name: "NextBinaryPay", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "userAddr", type: "address" }],
    name: "getUserBulkInfo",
    outputs: [
      { internalType: "string", name: "roundPoints", type: "string" },
      { internalType: "string", name: "roundEnter", type: "string" },
      { internalType: "string", name: "worth", type: "string" },
      { internalType: "string", name: "users", type: "string" },
      { internalType: "string", name: "dirEarned", type: "string" },
      { internalType: "string", name: "binaryEarned", type: "string" },
      { internalType: "string", name: "earnable", type: "string" },
      { internalType: "string", name: "insuranceStatus", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "userAddr", type: "address" },
      { internalType: "uint256", name: "fromRoundsAgo", type: "uint256" },
      { internalType: "uint256", name: "RoundsAgo", type: "uint256" },
    ],
    name: "getUserRoundInfo",
    outputs: [
      { internalType: "uint256[]", name: "points", type: "uint256[]" },
      { internalType: "string[]", name: "dirEarn", type: "string[]" },
      { internalType: "string[]", name: "binaryEarn", type: "string[]" },
      { internalType: "string[]", name: "dirFlash", type: "string[]" },
      { internalType: "string[]", name: "binaryFlash", type: "string[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "addr", type: "address" },
      { internalType: "uint256", name: "len", type: "uint256" },
    ],
    name: "getUserTree",
    outputs: [{ internalType: "address[]", name: "addrList", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "round", type: "uint256" }],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isClosed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAddr", type: "address" }],
    name: "resetWalletAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "roundId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stabilizedPointValue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stableToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "terminateAccount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "voteShutdown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "wrappedToken",
    outputs: [{ internalType: "contract IWERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
